### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by fromonesrc** [mattlqx/chef-duosecurity#14]
Sorry for the fake issue here @mattlqx. Trying to work with Slack on a bug in their GitHub integration that seems to only manifest after a repo has transferred ownership 😄 

Will close.

**Comment by fromonesrc** [comment]
Hi @mattlqx can you check if there is a hook at https://github.com/mattlqx/chef-duosecurity/settings/hooks that begins with `https://hooks.slack.com` and if so could you please remove it?

**Comment by mattlqx** [comment]
Yep, removed all the hooks.
